function  Gen_xyz (Atoms,Pos,foldername,filename)
species=Atoms;
xyz_out=Pos;
%   [charge multiplicity] = getcharge_gjf(filepath);
fid= fopen([foldername,'/',filename,'.xyz'],'w');
fprintf(fid, '%d \n', length(species));
fprintf(fid, '%s \n',['Generated by virtual chemist program']);
for ix=1:length(species)
fprintf(fid,'%s %10.9f %10.9f %10.9f \n',species{ix},xyz_out(ix,1),xyz_out(ix,2),xyz_out(ix,3));
end 
fprintf(fid,'\n');
fclose(fid);

end